config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  resources :urls
  resources :users
  

  root 'urls#index'

  get 'signup'  => 'users#create'
  match 'signup'  => 'users#create', :via => :post
  match 'signup'  => 'users#create', :via => :get
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/:key' => 'urls#redirect', :as => :redirect_url

end

app/models/url.rb
class Url < ActiveRecord::Base
    before_create :make_key
    belongs_to :user
    validate :valid_url

    def valid_url
        url = URI.parse(self.url) rescue false
        if !url.kind_of?(URI::HTTP) && !url.kind_of?(URI::HTTPS)
            errors.add(:url, "invalid url")
        end
    end

    def hit
        if self.hits.is_a? Numeric
            self.hits += 1
        else
            self.hits = 1
        end
        self.save
    end

    private
        def make_key
            self.key = random_str(6)
        end

        def random_str(length)
            
            random_str = ''
            
            for i in (0..length)

                # get a random 0, 1, or 2
                zero_one_or_two = Random.rand(3)

                # if 0, make a random lowercase
                if zero_one_or_two == 0
                    random_num = Random.rand(26) + 97
                    random_char = random_num.chr

                # if 1, make a random uppercase
                elsif zero_one_or_two == 1
                    random_num = Random.rand(26) + 65
                    random_char = random_num.chr

                # if 2, make a random 0-9 num
                else
                    random_num = Random.rand(10)
                    random_char = random_num.to_s
                end

                # append to randon_str
                random_str += random_char

            end

            random_str
        end
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :remember_token

    has_many :urls

    before_save {self.email = self.email.downcase}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :name, presence: true, length: { maximum: 50 }
    validates :email, 
    presence: true, 
    length: { maximum: 255 }, 
    format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }

    has_secure_password

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(self.remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_token, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    @user = User.find_by(email:email)
    if @user && @user.authenticate(password)
        # create new session
        log_in @user
        # remember of forget user based on checkbox
        params[:session][:remember] == '1' ? remember(@user) : forget(@user)
        # redirect to profile?
        redirect_to user_path(@user)
    else
        flash.now[:danger] = 'Invalid email/password combination'
        render 'new'
    end
  end

  def destroy
    if logged_in?
        log_out
        flash[:success] = 'successfully logged out!'
        redirect_to urls_path
    else
        flash[:success] = "You're not logged in, homie..."
        redirect_to urls_path
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

    def index
        @url = Url.new
    end

    def create
        @url = Url.new(url_params)

        # if user is logged in
        if logged_in?
            @url.user_id = @current_user.id
        end

        if @url.save
            redirect_to @url
        else
            render 'index'
        end
    end

    def show
        @base_url = request.base_url
        @url = Url.find(params[:id])
    end

    def redirect
        url = Url.find_by! key: params[:key]
        url.hit
        redirect_to url.url
    end

    private
        def url_params
            params.require(:url).permit(:url)
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    if request.post?
      @user = User.create(new_user_params)
        if @user.valid?
          flash[:success] = "You've signed up!"
          log_in(@user)
          remember(@user)
          redirect_to urls_path
      else
          render 'new'
      end
    else
      @user = User.new
      render 'new'
    end
  end

    def show
        @user = User.find(params[:id])
        @base_url = request.base_url
    end

  private
    def new_user_params
        params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user.
    def log_in(user)
        session[:user_id] = user.id
    end

    # Remembers a user in a persistent session.
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    # Returns the user corresponding to the remember token cookie.
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        !current_user.nil?
    end

    # Logs out the current user.
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
      © 2016 JeffCo
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav>
    <div class="nav-wrapper">
        <div class="container">
            <a href="#" class="brand-logo">ShortJeff</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><%= link_to "URLs", urls_path %></li>
                <% if logged_in? %>
                    <li><%= link_to current_user.name, user_path(current_user) %></li>
                    <li><%= link_to 'log out', logout_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to "log in", login_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | URLshortner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <main>
        <% if flash.any? %>
          <% flash.each do |name, msg| %>
            <p class="flash" hidden><%= msg %></p>
          <% end %>
        <% end %>

        <%= render 'layouts/navbar' %>

        <%= yield %>
        <div class="valign-wrapper">
            <div class="card-content valign center-block">
                <%= image_tag("jeff/jeff.jpg", class: "responsive-img center-align") %>
            </div>
        </div>
        
    </main>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_form_errors.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_url_form_errors.html.erb
<% if @url.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@url.errors.count, "error") %>.
        </div>
        <ul>
            <% @url.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_user_form_errors.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/urls/_form.html.erb
<%= form_for @url do |f| %>
    <%= render 'shared/url_form_errors' %>
    <div class="input-field col s12">
        <%= f.url_field :url %>
        <%= f.label :url %>
    </div>
    <div class="input-field col s12">
        <%= f.submit 'Submit', class: 'waves-effect waves-light btn' %>
    </div>
<% end %>

app/views/urls/index.html.erb
<div class="container">
    
    <% provide(:title, "Home") %>

    <h1 class="center">
        hello from url shortner this is jeff speaking
    </h1>

    <p>
        you know the drill. enter a long url, get a short url. use the form below.
    </p>

    <%= render 'form' %>

</div>

app/views/urls/show.html.erb
<% provide(:title, "Result") %>
<div class="container">
    <p>
        <%= @url.url %>
    </p>

    <p>
        <%= link_to @base_url + "/" + @url.key, @base_url + "/" + @url.key %>
    </p>
</div>

app/views/users/_urls.html.erb
<% if @user.urls != [] %>
    <ul class="collapsible popout" data-collapsible="accordion">
        <% @user.urls.each do |url| %>
            <li>
                <div class="collapsible-header"><%= url.key %></div>
                <div class="collapsible-body">
                    <p><b>Short: </b><%= link_to @base_url + "/" + url.key, @base_url + "/" + url.key %></p>
                    <p><b>Original: </b><%= url.url %></p>
                    <p><b>Hits: </b><%= url.hits %></p>
                </div>
            </li>
        <% end %>
    </ul>
<% else %>
    <p>
        You haven't created any shortened URLses yet :(
    </p>
<% end %>

app/views/users/new.html.erb
<% provide(:title, "New user") %>
<div class="container">
    <h1>Signup for this sweet URL shortner</h1>
    <p>Already a member? <%= link_to 'Log in here', login_path %></p>
    <p>It'll let you keep track of URL's you've shortened and hitcount, too.</p>

    <%= render 'form' %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
    <h1>
        <%= gravatar_for(@user) %>
        <%= @user.email %>
    </h1>
    <h3>Users URLses</h3>

    <%= render 'urls' %> 

</div>